version: "3"

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=customers-app-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./temp/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    command: serve
    depends_on: 
      db:
        condition: service_healthy
    environment:
    - DATABASE_URL=postgresql://postgres:postgres@db:5432/customers-app-db?sslmode=disable